---
- hosts: localhost
  gather_facts: no

  tasks:
  - ansible.controller.host:
      name: "{{ new_host }}"
      inventory: 3
      state: "{{ new_state }}"
      variables:
        ansible_host: "{{ new_ip }}"